development:
  debug: True
  headless: False
  browser_args: [
    '--disable-infobars',
    '--no-sandbox',
    '--disable-gpu',
    '--ignore-certificate-errors',
    '--ignore-ssl-errors',
    '--window-size=1980,1000',
    '--disk-cache-size=10485760',
    #    'blink-settings=imagesEnabled=false'
    '--disable-plugins'
  ]
  experimental_option: {
    prefs: {

    },
    excludeSwitches: ['enable-automation']
  }
  callback: {
    default: 'file',
    stores: {
      file: {
        name: 'boss.txt'
      },
      request: {
        url: 'http://127.0.0.1:5000/tasks/'
      }
    }
  }
  load_command_from_file: True

production:
  debug: False
  headless: True
  browser_args: [
    '--no-sandbox',
    '--disable-gpu',
  ]
  hub: [http://127.0.0.1, http://127.0.0.1]
